"""Migracion de datos nuevo

Revision ID: d2a28c7a6938
Revises: 
Create Date: 2026-06-26 14:41:06.127105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a28c7a6938'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_calificaciones')
    op.drop_table('respuestas_autoevaluacion')
    op.drop_table('autoevaluaciones_config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoevaluaciones_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('curso_id', sa.INTEGER(), nullable=False),
    sa.Column('trimestre', sa.INTEGER(), nullable=False),
    sa.Column('activo', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curso_id', 'trimestre')
    )
    op.create_table('respuestas_autoevaluacion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('config_id', sa.INTEGER(), nullable=False),
    sa.Column('estudiante_id', sa.INTEGER(), nullable=False),
    sa.Column('puntaje', sa.FLOAT(), nullable=True),
    sa.Column('fecha_respuesta', sa.DATETIME(), nullable=True),
    sa.Column('nota_final', sa.FLOAT(), nullable=True),
    sa.Column('retroalimentacion', sa.TEXT(), nullable=True),
    sa.Column('docente_id', sa.INTEGER(), nullable=True),
    sa.Column('fecha_calificacion', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['autoevaluaciones_config.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'estudiante_id')
    )
    op.create_table('historial_calificaciones',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('calificacion_id', sa.INTEGER(), nullable=False),
    sa.Column('nota_anterior', sa.FLOAT(), nullable=False),
    sa.Column('nota_nueva', sa.FLOAT(), nullable=False),
    sa.Column('docente_id', sa.INTEGER(), nullable=False),
    sa.Column('fecha_cambio', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['calificacion_id'], ['calificaciones.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
